### ISSUE TITLE
Use `IComparer<T>` instead of dynamic?

### ISSUE THREAD

**Issue by madelson** [masterjeef/rapid-priority-queue#1]
Did you consider using `IComparer<T>`/`Comparer<T>.Default` to compare queue elements instead of dynamic? This should speed things up and also allows for more flexibility.

**Comment by masterjeef** [comment]
Hi @madelson,

I agree with you, this is something that I have regretted for too long. I originally ported this code from Java and at the time I was very excited about operator overloading and dynamic (a little too excited to be honest). This excitement clouded my judgement and resulted in a poor choice.

I'm glad that you have expressed an interest in the project. I have committed the change, and a new Nuget Package has been released. (:

Regards,

Masterjeef
